package com.testing.ground.constant.misc;

public interface AppConstant {
    long JWT_EXPIRATION_MS = 15 * 60 * 1000;

    // Email template names
    String EMAIL_TEMPLATE_NAME_PASSWORD_RESET = "PASSWORD_RESET";
    String EMAIL_TEMPLATE_NAME_WELCOME = "WELCOME";
    String EMAIL_TEMPLATE_NAME_VERIFICATION = "VERIFICATION";
    String EMAIL_TEMPLATE_NAME_SOCIAL_LOGIN = "SOCIAL_LOGIN";
    String EMAIL_TEMPLATE_NAME_SOCIAL_LOGIN_VERIFICATION = "SOCIAL_LOGIN_VERIFICATION";
    String EMAIL_TEMPLATE_NAME_SOCIAL_LOGIN_WELCOME = "SOCIAL_LOGIN_WELCOME";
    String EMAIL_TEMPLATE_NAME_SOCIAL_LOGIN_PASSWORD_RESET = "SOCIAL_LOGIN_PASSWORD_RESET";
    String EMAIL_TEMPLATE_NAME_SOCIAL_LOGIN_VERIFICATION_FAILED = "SOCIAL_LOGIN_VERIFICATION_FAILED";
    String EMAIL_TEMPLATE_NAME_SOCIAL_LOGIN_VERIFICATION_SUCCESS = "SOCIAL_LOGIN_VERIFICATION_SUCCESS";
    String EMAIL_TEMPLATE_NAME_SOCIAL_LOGIN_VERIFICATION_EXPIRED = "SOCIAL_LOGIN_VERIFICATION_EXPIRED";

}
