
Hibernate:
    create table app_user_roles (
        app_user_id bigint not null,
        roles_id bigint not null,
        primary key (app_user_id, roles_id)
    )

Hibernate:
    create table user_role (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    )

Hibernate:
   alter table if exists app_user_roles
      add constraint FKqrsd1wnok912tg9bakqtit7j3
      foreign key (roles_id)
      references user_role
Hibernate:
   alter table if exists app_user_roles
      add constraint FKkwxexnudtp5gmt82j0qtytnoe
      foreign key (app_user_id)
      references app_user

 select * from app_user
 select * from role
select * from app_user_roles

-- Roles
INSERT INTO user_role (name) VALUES ('ADMIN'), ('USER'), ('GUEST');

-- Users
INSERT INTO app_user (username, password) VALUES ('admin', '{bcrypt}hashed_password');

INSERT INTO app_user (username, password) VALUES ('admin', '{noop}amit');
INSERT INTO app_user (username, password) VALUES ('amit', '{noop}amit');
INSERT INTO app_user (username, password) VALUES ('guest', '{noop}amit');

-- Assigning roles to users
INSERT INTO app_user_roles (app_user_id, roles_id) VALUES (4, 1); -- ADMIN role
INSERT INTO app_user_roles (app_user_id, roles_id) VALUES (5, 2); -- USER role
INSERT INTO app_user_roles (app_user_id, roles_id) VALUES (6, 3); -- GUEST role


