apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rabbitmq-to-kafka
  labels:
    app: software-st1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: software-st1
  template:
    metadata:
      labels:
        app: software-st1
    spec:
      containers:
        - name: demo-rabbitmq-to-kafka
          image: containers.cisco.com/amigaura/demo-rabbitmq-to-kafka:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
      imagePullSecrets:
        - name: amigaura-pull-secret
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: demo-rabbitmq-to-kafka-service
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 80
#      targetPort: 8080
#  selector:
#    app: software-st1