#logging:
#  level:
#    root: ERROR
#    org.springframework: ERROR
#    com.demo: DEBUG
#    com.demo: INFO

kafka:
  #  bootstrap-servers: localhost:9092
  #  bootstrap-servers: swx-kfk-stg1-2.cisco.com:9093,swx-kfk-stg1-1.cisco.com:9093,swx-kfk-stg2-1.cisco.com:9093,swx-kfk-stg2-2.cisco.com:9093
  bootstrap-servers: swx-kfk-stg2-1.cisco.com:9093
  security:
    protocol: SSL
  topic-0:
    topic-name: test_topic-0
    consumer-group-id: topic-0-consumer-group
    concurrency: 3  # Increase concurrency to allow multiple threads to consume messages. Increase based on CPU cores
    max-attempts: 3 # Maximum number of attempts to process a message. Default is 2.
    initial-interval: 1000 # Initial interval in milliseconds. Default is 2000.
    multiplier: 1.0 # Multiplier to apply to the previous interval. Default is 2.0.
    max-interval: 8000 # Maximum interval in milliseconds. Default is 8000.
  topic-1:
    topic-name: test_topic-1
    consumer-group-id: topic-1-consumer-group
    concurrency: 3
    max-attempts: 2
    initial-interval: 2000
    multiplier: 2.0
    max-interval: 8000
  topic-2:
    topic-name: test_topic-2
    consumer-group-id: topic-2-consumer-group


